### ISSUE TITLE
crash on running Discline.py

### ISSUE THREAD

**Issue by anna328p** [MitchWeaver/Discline#31]
```bash
$ python3 Discline.py
```
```python
Traceback (most recent call last):
  File "Discline.py", line 15, in <module>
    from discord import ChannelType
  File "/usr/lib/python3.7/site-packages/discord/__init__.py", line 20, in <module>
    from .client import Client, AppInfo, ChannelPermissions
  File "/usr/lib/python3.7/site-packages/discord/client.py", line 38, in <module>
    from .state import ConnectionState
  File "/usr/lib/python3.7/site-packages/discord/state.py", line 36, in <module>
    from . import utils, compat
  File "/usr/lib/python3.7/site-packages/discord/compat.py", line 32
    create_task = asyncio.async
                              ^
SyntaxError: invalid syntax
```

**Comment by Ayuei** [comment]
I had the same problem. If you take a look at the python3.7 release notes:
```async and await are now reserved keywords on python3.7. ```
You will need to downgrade to python3.6.X or lower in order to use it or you will need to rewrite the source code.
