### ISSUE TITLE
Problem with running DISCLINE 

### ISSUE THREAD

**Issue by spinfire** [MitchWeaver/Discline#36]
`python3.6 Discline.py`

then
```Checking for updates...
Already up to date!

Starting...
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/discord/http.py", line 258, in static_login
    data = yield from self.request(Route('GET', '/users/@me'))  File "/usr/local/lib/python3.6/site-packages/discord/http.py", line 200, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: UNAUTHORIZED (status code: 401): 401: Unauthorized

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Discline.py", line 211, in <module>
    if __name__ == "__main__": main()
  File "Discline.py", line 200, in main
    try: gc.client.run(token, bot=False)
  File "/usr/local/lib/python3.6/site-packages/discord/client.py", line 519, in run
    self.loop.run_until_complete(self.start(*args, **kwargs))
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.6/site-packages/discord/client.py", line 490, in start
    yield from self.login(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/discord/client.py", line 416, in login
    yield from getattr(self, '_login_' + str(n))(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/discord/client.py", line 346, in _login_1
    data = yield from self.http.static_login(token, bot=is_bot)
  File "/usr/local/lib/python3.6/site-packages/discord/http.py", line 262, in static_login
    raise LoginFailure('Improper token has been passed.') from e
discord.errors.LoginFailure: Improper token has been passed.
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x10666e8d0>

**Comment by Nevexo** [comment]
Your token is wrong.

**Comment by humboldt123** [comment]
I get this error as well. I know for a fact that my token is correct!

**Comment by Nevexo** [comment]
@humboldt123 Maybe try NatTupper's fork https://github.com/NatTupper/dline
