### ISSUE TITLE
AttributeError: 'NoneType'

### ISSUE THREAD

**Issue by RootOperator** [MitchWeaver/Discline#48]
whenever I try to launch Discline it will say this

`Checking
 for updates...
Already up to date!
Starting...`

then after a while it gives me this error:

`Ignoring exception in on_ready
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/discord/client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "Discline.py", line 126, in on_ready
    await print_screen()
  File "/home/arch/Discline/ui/ui.py", line 27, in print_screen
    await print_top_bar(left_bar_width)
  File "/home/arch/Discline/ui/ui.py", line 80, in print_top_bar
    online_count = str(await gc.client.get_online())
  File "/home/arch/Discline/client/client.py", line 73, in get_online
    if not self.get_current_server() == None:
  File "/home/arch/Discline/client/client.py", line 36, in get_current_server
    if server.name.lower() == self.__current_server:
AttributeError: 'NoneType' object has no attribute 'lower'
`
I'm running this on python3.6.7
OS: Arch

**Comment by Wei-ss** [comment]
Getting the same error on version 3.6.8.

```python
Ignoring exception in on_ready
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/discord/client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "Discline.py", line 126, in on_ready
    await print_screen()
  File "/home/tevra/Downloads/Discline/ui/ui.py", line 27, in print_screen
    await print_top_bar(left_bar_width)
  File "/home/tevra/Downloads/Discline/ui/ui.py", line 80, in print_top_bar
    online_count = str(await gc.client.get_online())
  File "/home/tevra/Downloads/Discline/client/client.py", line 73, in get_online
    if not self.get_current_server() == None:
  File "/home/tevra/Downloads/Discline/client/client.py", line 36, in get_current_server
    if server.name.lower() == self.__current_server:
AttributeError: 'NoneType' object has no attribute 'lower'
```
