### ISSUE TITLE
SyntaxError: invalid syntax on storing token

### ISSUE THREAD

**Issue by Wei-ss** [MitchWeaver/Discline#52]
I'm having the same error as #31. Manjaro seems to be using Python 3.7, despite the fact it's not in my package list.

```python
~/Discline >>> python3 Discline.py --store-token                                                                          Traceback (most recent call last):
  File "Discline.py", line 15, in <module>
    from discord import ChannelType
  File "/usr/lib/python3.7/site-packages/discord/__init__.py", line 20, in <module>
    from .client import Client, AppInfo, ChannelPermissions
  File "/usr/lib/python3.7/site-packages/discord/client.py", line 38, in <module>
    from .state import ConnectionState
  File "/usr/lib/python3.7/site-packages/discord/state.py", line 36, in <module>
    from . import utils, compat
  File "/usr/lib/python3.7/site-packages/discord/compat.py", line 32
    create_task = asyncio.async
                              ^
SyntaxError: invalid syntax
```
<details>
<summary>All python-related packages</summary>
<br>
python-levenshtein, python-pip, python-plexapi, python-pywal, python2-fuzzywuzzy, python2-gmusicapi, python2-gpsoauth, python2-mechanicalsoup, python2-pafy-git, python2-proboscis, python2-pychromecast-git, python2-pyspotify, python2-soundcloud-git, python2-spotipy, python2-validictory, python2-youtube-dl-git, python35

**Comment by Wei-ss** [comment]
Realized I could state which python package runs the command with `python3.6` instead of `python3`. May be worth updating the installation section?

Also worth of note is that pip3 doesn't work. It throws a "no module named discord" error.
I had to use `curl https://bootstrap.pypa.io/get-pip.py | sudo -H python3.6` to get pip for python 3.6 and install dependencies through that.
